#!/bin/bash
echo "Reset BIG-IP admin password"
echo "Assuming the AWS ssh private key is in folder \$WS, use export command to set value of environment variable WS="
echo "The AWS ssh private ket file name is MyKeyPair-\$emailid.pem, use export command to set value of environment variable emailid"
echo "BIG-IP admin password is set in environment variable bigip_password"
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $WS/MyKeyPair-$emailid.pem admin@$1 show sys mcp-state field-fmt |grep -qE 'phase.+running'
if [ $? == 0 ]; then
 echo 'resetting password'
 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $WS/MyKeyPair-$emailid.pem admin@$1 modify /auth user admin password $bigip_password
 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $WS/MyKeyPair-$emailid.pem admin@$1 save /sys config
 else
 echo 'not running, try again'
fi
